eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost/8761/eureka/
  instance:
      hostname: localhost

com:
  mugh:
    port: 4040
    
  training:
    tax: 16
